name: demo
description: AutoSizeText Demo App

version: 1.0.0+2

environment:
  sdk: ">=2.10.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter

  auto_size_text:
    path: ../

  bottom_navy_bar: ^5.6.0
  material_design_icons_flutter: ^4.0.5755

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true

publish_to: none